stages:
  preprocess:
    cmd: poetry run preprocess --raw-data-path data/raw/cr_loan2.csv --preprocessed-data-path
      data/clean/clean_cr_loan.csv
    deps:
    - credit_default_prediction/preprocess.py
    - data/raw/cr_loan2.csv
    outs:
    - data/clean/clean_cr_loan.csv
  split:
    cmd: poetry run split --preprocessed-data-path data/clean/clean_cr_loan.csv --train-path
      data/train.csv --test-path data/test.csv
    deps:
    - credit_default_prediction/split.py
    - data/clean/clean_cr_loan.csv
    outs:
    - data/test.csv
    - data/train.csv
    params:
    - split
  train:
    cmd: poetry run train --train-dataset-path data/train.csv --model-path model.pkl
    deps:
    - credit_default_prediction/train.py
    - data/train.csv
    outs:
    - model.pkl
  evaluate:
    cmd: poetry run evaluate --model-path model.pkl --test-dataset-path data/test.csv
    deps:
    - credit_default_prediction/evaluate.py
    - data/test.csv
    - model.pkl
plots:
- dvclive/plots/metrics:
    x: step
- dvclive/plots/custom/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    x_label: Actual labels
    y_label: Predicted labels
- dvclive/plots/sklearn/roc.json:
    template: simple
    x: fpr
    y: tpr
    title: Receiver operating characteristic (ROC)
    x_label: False Positive Rate
    y_label: True Positive Rate
metrics:
- dvclive/metrics.json
