preprocess:
  important_columns:
    - person_income
    - person_emp_length
    - person_age
    - loan_percent_income
    - loan_int_rate
    - loan_grade
    - loan_amnt
    - loan_intent
    - person_home_ownership
    - loan_status

split:
  test_size: 0.3
  random_state: 123

train:
  learning_rate: 0.2
  max_depth: 6
  min_child_weight: 5
