name: CML
on: [push]
permissions:
  # Essential to allow CML to write in pull requests via the GitHub token
  pull-requests: write
  # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
  contents: write

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install libc6
      - uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.12.5
          poetry-version: 1.8.3
          install-args: --with dev
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - name: Setup DagsHub DVC remote
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_TOKEN }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_TOKEN }}
      - name: Linting
        run: |
          poetry run flake8
          poetry run black --check .
      - name: Run tests
        run: |
          poetry run pytest
      - name: Train Model
        run: |
          dvc pull --run-cache
          dvc repro
          dvc commit --force
          dvc push
      - name: Commit pipeline changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Reproduce training pipeline
          file_pattern: .
      - name: Create CML report
        if: github.ref_name != 'main'
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics: workflow vs. main" >> report.md
          git fetch --depth=1 origin main:main

          dvc metrics diff --md main >> report.md

          echo "## Plots" >> report.md
          echo "### Class confusions" >> report.md
          dvc plots diff \
            --target dvclive/plots/custom/confusion_matrix.json \
            --show-vega main > vega.json
          vl2png vega.json -s 1.5 > confusion-plot.png
          echo '![](./confusion-plot.png "Confusion matrices comparison")' >> report.md

          echo "### ROC curves" >> report.md
          dvc plots diff \
            --target dvclive/plots/sklearn/roc.json \
            --show-vega main > vega.json
          vl2png vega.json -s 1.5 > roc-plot.png
          echo '[](./roc-plot.png "ROC curves comparison")' >> report.md

          cml comment create report.md
