name: CML
on:
  push:
    paths:
      - .github/workflows/cml.yaml
      - data/**
      - credit_default_prediction/**
      - pyproject.toml
      - poetry.lock
      - dvc.yaml
      - dvc.lock
  workflow_dispatch:

permissions:
  # Essential to allow CML to write in pull requests via the GitHub token
  pull-requests: write
  # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
  contents: write

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install libc6
      - uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.12.7
          poetry-version: 1.8.3
      - uses: iterative/setup-cml@v1
      # - uses: iterative/setup-dvc@v1
      - name: Setup DagsHub DVC remote
        run: |
          poetry run dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_TOKEN }}
          poetry run dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_TOKEN }}
      - name: Train Model
        run: |
          poetry run dvc pull --run-cache --allow-missing
          poetry run dvc repro
          poetry run dvc commit --force
          poetry run dvc push
      - name: Commit pipeline changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Reproduce training pipeline
          file_pattern: .
      - name: Create CML report
        if: github.ref_name != 'main'
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics: workflow vs. main" >> report.md
          git fetch --depth=1 origin main:main

          poetry run dvc metrics diff --md main >> report.md
          cml comment create report.md || { echo 'CML comment creation failed'; exit 1; }
