name: Code quality
on:
  push:
    paths:
      - credit_default_prediction/**.py
      - scripts/**.py
      - .github/workflows/code_quality.yaml
      - pyproject.toml
      - poetry.lock

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-system-deps
      - name: Install dependencies
        run: poetry install

      - name: Linting
        run: make lint
