name: Code quality
on:
  push:
    paths:
      - credit_default_prediction/**.py
      - scripts/**.py
      - .github/workflows/code_quality.yaml
      - pyproject.toml
      - poetry.lock

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13.3
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install libc6
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.8.3
          export PATH="$HOME/.local/bin:$PATH"
      - name: Install dependencies
        run: poetry install
      - name: Linting
        run: make lint
