name: Tests
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-system-deps
      - name: Install dependencies
        run: poetry install
      - name: Tests
        run: poetry run pytest
